"""
0xDownloader - Configuration
Handles all application settings including window dimensions, fonts, colors, layout, animations, download engine parameters, and updater settings
"""

# ============================================================================
# APP SETTINGS & CONSTANTS
# ============================================================================

# --- WINDOW & SYSTEM ---
TITLE_TEXT = "0xDownloader"
WINDOW_WIDTH = 1020
WINDOW_HEIGHT = 600
WINDOW_GEOMETRY = f"{WINDOW_WIDTH}x{WINDOW_HEIGHT}"

# --- FONTS ---
FONT_TITLE = ("Consolas", 26, "bold")
FONT_UI = ("Segoe UI", 10)
FONT_UI_BOLD = ("Segoe UI", 12, "bold")
FONT_UI_SMALL = ("Segoe UI", 9)
FONT_UI_SMALL_BOLD = ("Segoe UI", 9, "bold")
FONT_LOG = ("Consolas", 8)
FONT_PERCENTAGE = ("Impact", 35)
FONT_ICON = ("Segoe UI", 14)
FONT_BIG_ICON = ("Roboto", 70, "bold")

# --- COLORS: MAIN THEME ---
COLOR_BG = "#050505"
COLOR_INPUT_BG = "#11151A"
COLOR_DEFAULT_THEME = "#444444"
COLOR_TEXT_WHITE = "#FFFFFF"
COLOR_TEXT_BLACK = "#000000"
COLOR_TEXT_DIM = "#666666"
COLOR_TEXT_DARK = "#444444"

# --- COLORS: BUTTONS & INTERACTION ---
COLOR_BTN_DEFAULT = "#333333"
COLOR_BTN_HOVER = "#222222"
COLOR_BTN_ABORT = "#FF4444"
COLOR_BTN_DISABLED_TEXT = "#777777"
COLOR_BTN_PAUSE = "#FFB64D"
COLOR_BTN_RESUME = "#30B34A"

# --- COLORS: STATUS INDICATORS ---
COLOR_UPDATING = "#1f6feb"
COLOR_ERROR = "#FF4444"
COLOR_WARNING = "#FFB64D"
COLOR_SUCCESS = "#30B34A"
COLOR_MERGING = "#33CCFF"
COLOR_COMING_SOON = "#FF9900"

# --- COLORS: LOG SYSTEM ---
LOG_BG = "#0a0a0a"
LOG_COLOR_TIME = "#666666"
LOG_COLOR_SEP = "#0a0a0a"
LOG_COLOR_HEADER = "#FFFFFF"
LOG_COLOR_DEFAULT = "#888888"
LOG_COLOR_INFO = "#00CCFF"
LOG_COLOR_SUCCESS = "#30B34A"
LOG_COLOR_ERROR = "#FF4444"
LOG_COLOR_WARN = "#FFB64D"
LOG_COLOR_FFMPEG = "#AA55FF"

# --- LAYOUT DIMENSIONS ---
LAYOUT_INPUT_X = 60
LAYOUT_INPUT_Y = 100
LAYOUT_INPUT_W = 700
LAYOUT_INPUT_H = 60
LAYOUT_BTN_W = 180
LAYOUT_GAP = 20
LAYOUT_CARD_W = 220
LAYOUT_CARD_H = 80
LAYOUT_COL_GAP = 20
LAYOUT_ROW_GAP = 15
LAYOUT_RING_X = 250
LAYOUT_RING_Y = 380
LAYOUT_RING_RADIUS = 110
LAYOUT_RING_WIDTH = 15
LAYOUT_FOLDER_W = 160
LAYOUT_FOLDER_H = 40

# --- ANIMATION SETTINGS ---
ANIM_SPEED_LERP = 0.25
ANIM_SPEED_LIFT = 0.2
ANIM_SPEED_RING = 0.40
ANIM_HUE_SPEED = 0.002

# --- LOGIC CONSTANTS ---
GRID_SPACING = 16
LOADING = [0, 2, 4, 6, 8, 1, 3, 5, 7]

# --- DOWNLOAD ENGINE SETTINGS ---
DL_FOLDER_NAME = "downloads"
DL_CONCURRENT_FRAGMENTS = 4
DL_SPEED_HISTORY_LEN = 20
DL_SMOOTHING_WINDOW = 10
DL_SOCKET_TIMEOUT = 30
DL_RETRIES = 20
DL_FILE_ACCESS_RETRIES = 5
DL_UI_UPDATE_DELAY = 1.5
DL_AUDIO_QUALITY = "192"
DL_AUDIO_BITRATE = "192k"
DL_HTTP_CHUNK_SIZE = 10485760  # 10MB

# --- THROTTLING SETTINGS ---
THROTTLE_RETRY_DELAY = 60
THROTTLE_MAX_RETRIES = 3
THROTTLE_BACKOFF_MULTIPLIER = 2

# ============================================================================
# CHECKER & UPDATER SETTINGS
# ============================================================================

# --- CHECKER UI ---
CHECKER_MIN_DISPLAY_TIME = 4.0
CHECKER_WINDOW_WIDTH = 450
CHECKER_WINDOW_HEIGHT = 150
CHECKER_PROGRESS_LENGTH = 350

# --- CHECKER FONTS & COLORS ---
FONT_CHECKER = ("Roboto", 11)
COLOR_PROGRESS_BAR = "#238636"
COLOR_THROUGH = "#E0E0E0"
COLOR_BORDER = "#CCCCCC"

# --- UPDATER UI ---
UPDATER_TITLE_TEXT = "0xDownloader Updater"
UPDATER_WINDOW_WIDTH = 900
UPDATER_WINDOW_HEIGHT = 600
UPDATER_CARD_WIDTH = 190
UPDATER_PROGRESS_STEPS = 50
UPDATER_BLINK_INTERVAL = 30

# --- UPDATER COLORS ---
COLOR_TERMINAL_BG = "#0c0c0c"
COLOR_ACCENT = "#7C4DFF"
COLOR_BLINK = "#2b99ff"
COLOR_CRITICAL = "#FF4D4D"

UPDATER_RAINBOW_COLORS = [
    "#FF0000",
    "#FF7F00",
    "#FFFF00",
    "#00FF00",
    "#0000FF",
    "#9400D3",
]

UPDATER_RAINBOW_SPEED = 0.01
UPDATER_RAINBOW_WAVE_WIDTH = 0.03

# --- UPDATER FONTS ---
FONT_UPDATER_TITLE = ("Segoe UI", 22, "bold")
FONT_UPDATER = ("Segoe UI", 12, "bold")
FONT_PACK_TITLE = ("Segoe UI", 10, "bold")
FONT_VER_UPDATER = ("Segoe UI", 8)
FONT_LOG_UPDATER = ("Consolas", 9)
